[build]
    functions = "functions"
    included_files = ["functions/build/*", "functions/uploads/*"]
    publish = "functions/build"
[[redirects]]
    from = "/*"
    status = 200
    to = "/.netlify/functions/app/:splat"

# [[redirects]]
#     from = "/*"
#     to = "/index"
#     status = 200